# Generated by Django 3.2.5 on 2024-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmodel',
            name='coal_type',
            field=models.CharField(choices=[('Anthracite', 'Anthracite'), ('Bituminous', 'Bituminous'), ('Sub-bituminous', 'Sub-bituminous'), ('Lignite', 'Lignite'), ('None', 'None')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fuelmodel',
            name='fuel',
            field=models.CharField(choices=[('Diesel Oil', 'Diesel Oil'), ('LPG', 'LPG'), ('Petrol', 'Petrol'), ('Coal', 'Coal'), ('Other', 'Other')], max_length=50),
        ),
    ]
